[[redirects]]
  from = "/api/*"
  to = "https://privly-backend.vercel.app/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/webhook/*"
  to = "https://privly-backend.vercel.app/webhook/:splat"
  status = 200
  force = true

# SPA fallback - serve index.html for all routes that don't match files
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/images/*"
  to   = "/images/:splat"
  status = 200

