[[redirects]]
  from = "/api/*"
  to = "https://privly-backend.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/webhook/*"
  to = "https://privly-backend.onrender.com/webhook/:splat"
  status = 200
  force = true

# SPA fallback - serve index.html for all routes that don't match files
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200